apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoh-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contoh
  template:
    metadata:
      labels:
        app: contoh
    spec:
      containers:
      - name: contoh-testing-container
        image: debian:buster-slim
        command: ["bash", "-c", "while true; do echo \"Hello\"; echo \"EXAMPLE_ENV: $EXAMPLE_ENV\"; sleep 5; done"]
        env:
        - name: EXAMPLE_ENV
          value: Hello Bro
