apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
spec:
  containers:
  - image: nginx:1.19.0
    name: app
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: application.database
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: application.port