apiVersion: v1
kind: Pod
metadata:
  name: configured-pod-2
spec:
  containers:
  - image: nginx:1.19.0
    name: app
    volumeMounts:
    - name: properties-volume
      mountPath: /config
  volumes:
  - name: properties-volume
    configMap:
      name: app-properties