apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  maxReplicas: 3
  minReplicas: 1
  metrics: 
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 10Mi